######################################################################
##  Alarm
######################################################################
- alias: 'Alarm'

  trigger:
    - platform: state
      entity_id: binary_sensor.window_door_sensor
      to: 'on'

  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_boolean.night_mode_security
        state: 'on'
      - condition: and
        conditions:
        - condition: state
          entity_id: input_boolean.away_guard_mode
          state: 'on'
        - condition: state
          entity_id: input_boolean.guest_mode
          state: 'off'

  action:
    - service: notify.notify
      data_template:
        title: "\U0001F534\U0001F534\U0001F534 ALERT \U0001F534\U0001F534\U0001F534"
        message: "\U0001F46E Intrusion detected"
    - service: script.dog_bark
