######################################################################
##  Alarm
######################################################################
- alias: 'Alarm'
  trigger:
    - platform: state
      entity_id: binary_sensor.window_door_sensor
      to: 'on'
    - platform: state
      entity_id: binary_sensor.vibration_3
      to: 'on'
      
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_boolean.night_mode_security
        state: 'on'
      - condition: and
        conditions:
        - condition: state
          entity_id: input_boolean.away_guard_mode
          state: 'on'
        - condition: state
          entity_id: input_boolean.guest_mode
          state: 'off'

  action:
    - service: script.notify_engine
      data_template:
        title: '{{"\U0001F534\U0001F534\U0001F534"}} ALERT {{"\U0001F534\U0001F534\U0001F534"}}'
        value1: '{{"\U0001F46E"}} Intrusion detected'
        ios_category: "alarm"

    - service: script.dog_bark

- alias: Stop dog
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: STOP_ALARM
  action:
    - service: media_player.media_stop
      entity_id: media_player.living_room_speaker

- alias: Switch off Alarm
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: SWITCH_OFF_ALARM
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.away_guard_mode
    - service: input_boolean.turn_off
      entity_id: minput_boolean.night_mode_security
