- alias: 'activate wash completed input boolean'
  trigger:
    platform: state
    entity_id: binary_sensor.washer_wash_completed
    to: 'on'

  action: 
    - service: input_boolean.turn_on
      entity_id: input_boolean.clothes_outside


- alias: 'remove clothes'
  trigger:
    - platform: state
      entity_id: sensor.climacell_precipitation_type
      to: 'rain'
    - platform: sun
      event: sunset
      offset: "-00:45:00"
  
  condition:
    - condition: state
      entity_id: input_boolean.clothes_outside
      state: 'on'
    - condition: state
      entity_id: group.family
      state: home
  
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.clothes_outside
    - service: script.say
      data_template:
        message: >
          {% if trigger.entity_id == 'sensor.climacell_precipitation_type' %}
            It is raining, remove your clothes from outside
          {% else %}
            It is time to remove your clothes from outside
          {% endif %}
    - service: notify.notify
      data_template:
        title: Remove your clothes
        message: >
          {% if trigger.entity_id == 'sensor.climacell_precipitation_type' %}
            It is raining, remove your clothes from outside
          {% else %}
            It is time to remove your clothes from outside
          {% endif %}
