######################################################################
##  Watering system
######################################################################
- alias: 'Watering System'

  trigger:
    - platform: sun
      event: sunset
      offset: "01:00:00"

  condition:
    - condition: time
      weekday:
        - mon
        - wed
        - fri
        - sun

  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.watering_system

- alias: 'Turn on water pump'
  
  trigger:
    platform: state
    entity_id: input_boolean.watering_system
    to: 'on'

  action:
    - service: script.notify_engine
      data_template:
        title: '{{"\U0001F4A7"}} Watering time'
        value1: '{{"\U0001F331"}} taking care of your flowers'
        who: 'gianluca'
    - delay: 
        minutes: 1
    - service: input_boolean.turn_off
      entity_id: input_boolean.watering_system

- alias: 'Turn off water pump'
  
  trigger:
    platform: state
    entity_id: input_boolean.watering_system
    to: 'off'
  
  action:
    - service: input_datetime.set_datetime
      data_template:
        entity_id: input_datetime.irrigation_last_time
        date: "{{ now().strftime('%Y-%m-%d') }}"
        time: "{{ now().strftime('%H:%M:%S') }}"

    - service: script.notify_engine
      data_template:
        title: '{{"\U0001F4A7"}} Watering time finished'
        value1: '{{"\U0001F331"}} switched off water pump, all ok'
        who: 'gianluca'